### ISSUE TITLE
specificEnthalpy_pT gives inconsistent results

### ISSUE THREAD

**Issue by casella** [CoolProp/ExternalMedia#17]
Try this simple test case:

package Test
package HeliumCoolProp 
    "Helium model from NIST RefProp database via ExternalMedia/CoolProp"
  extends ExternalMedia.Media.CoolPropMedium(
    mediumName = "Helium",
    substanceNames = {"He"},
    ThermoStates=Modelica.Media.Interfaces.Choices.IndependentVariables.ph);
end HeliumCoolProp;

  model Test1
    package Medium = HeliumCoolProp;
    Medium.AbsolutePressure p = 4e5;
    Medium.Temperature T = 4;
    Medium.SpecificEnthalpy h = Medium.specificEnthalpy_pT(p,T);
    Medium.ThermodynamicState state = Medium.setState_ph(p,h);
    Medium.Temperature T2 = Medium.temperature(state);
  end Test1;
end Test;

In principle, T should be equal to T2. Instead, T2 turns out to be 5.46 K instead of 4 K. It turns out that specificEnthalpy_pT(4e5,4) returns 7430 instead of 218. What is wrong with that function?

**Comment by ibell** [comment]
Maybe a bug in CoolProp?  Can you check?

On Wed, Jan 27, 2016 at 8:19 AM, Francesco Casella <notifications@github.com

**Comment by JonWel** [comment]
When using Julia 0.4 wrapper:

``` Julia
julia> h = PropsSI("H","P",4e5,"T",4,"Helium")
218.14620463403665

julia> PropsSI("T","P",4e5,"H",h,"Helium")
4.000000000000997
```

Which is the correct expected result

This 7430.89 enthalpy is not the good one:

``` Julia
julia> PropsSI("T","P",4e5,"H",7430.89,"Helium")
5.4669735288168315
```

With low level interface:

``` Julia
julia> using CoolProp
julia> handle = AbstractState_factory("HEOS", "Helium")
0
julia> input_pair = get_input_pair_index("PT_INPUTS")
9
julia> output = CoolProp.get_param_index("H")
34
julia> AbstractState_update(handle,input_pair,4e5,4)
julia> AbstractState_keyed_output(handle,output)
218.14620463403665
julia> CoolProp.AbstractState_free(handle)
```

It works also correctly

**Comment by JonWel** [comment]
I reproduce this strange result in `ExternalMedia` with the sample code.
The value computed for `h` is 7430.89 and the one for `T2` is -267.683.

**Comment by JonWel** [comment]
I reproduce this strange result in `ExternalMedia` with the sample code.
The value computed for `h` is 7430.89 and the one for `T2` is -267.683°C.

I also made more tests:

``` Modelica
Medium.ThermodynamicState state1 = Medium.setState_pT(p,T);
Medium.SpecificEnthalpy h = Medium.specificEnthalpy(state1);
Medium.ThermodynamicState state = Medium.setState_ph(p,h);
Medium.Temperature T2 = Medium.temperature(state);
```

Gives the same problem with `h` and `T2`.

`specificEnthalpy_pT` is defined there:
https://github.com/CoolProp/ExternalMedia/blob/master/Modelica/ExternalMedia%203.2.1/Media/BaseClasses/ExternalTwoPhaseMedium.mo#L477

It calls `specificEnthalpy_pT_state` and `setState_pT`

The call to `setState_pT` is: `state=setState_pT(p=p, T=T, phase=phase)`
This `phase` option is not used in this `coolpropsolver.cpp` implementation, but the second test I've done by calling this function directly gives same result and `basesolver.cpp` does not have this `phase` option neither. This is something that was already the case with `CoolProp 4`.

For the `CoolProp` solver, `setState_pT` is defined there:
https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.cpp#L552

And should update in `CoolProp` like this:
`state->update(CoolProp::PT_INPUTS,p,T);`

Which seems legit to me.

The retrieving of the `h` value is done by `h := specificEnthalpy(state);`.

And in `CoolPropSolver::postStateChange` this value is retrieved by `properties->h = state->hmass();`
Which is clearly the specific enthalpy.

**Comment by JonWel** [comment]
There is a problem when updating the state:

``` modelica
Medium.ThermodynamicState state1 = Medium.setState_pT(p,T);
```

In the example. (`Medium.specificEnthalpy_pT(p,T)` calls this function internally to make the state update).
The enthalpy given of `7430.89` is in fact constant whatever the temperature imput. Which is not good at all and the "5.46 K instead of 4 K" could have been a way larger difference (273.15K will also gives 7430.89).

I'll try to have a deeper look  in the next days. This is a big problem.

**Comment by ibell** [comment]
Can you replicate this behavior with calls to PropsSI?  That would help us
track down where the problem comes from.

**Comment by JonWel** [comment]
@ibell The test of PropSI (through Julia's wrapper, see my first comment) gives the correct result.

**Comment by ibell** [comment]
Interestingly, helium has some consistency issues:
http://www.coolprop.org/dev/fluid_properties/fluids/Helium.html#consistency-plots

**Comment by JonWel** [comment]
There is something going wrong in the `ExternalMedia` `pT update`:

Here is the code (C++) I tested:

``` C++
std::cout << "1) ExternalMedia Fluid Constants" << std::endl;
printFluidConstants("Helium", "CoolProp", "He");

std::cout << "\n2.0)  ExternalMedia Helium pT input" << std::endl; //|debug=100
TwoPhaseMedium_setState_pT_C_impl(4e5, 4, pointer, "Helium", "CoolProp", "Helium");
printValues(pointer);

std::cout << "\n2.1)  ExternalMedia Helium ph input" << std::endl;
TwoPhaseMedium_setState_ph_C_impl(4e5, 218.14620463403665, 2, pointer, "Helium", "CoolProp", "Helium");
printValues(pointer);

std::cout << "2.2) CoolProp AbstractState Helium" << std::endl;
shared_ptr<CoolProp::AbstractState> Water(CoolProp::AbstractState::factory("HEOS","Helium"));
Water->update(CoolProp::PT_INPUTS, 4e5, 4);
std::cout << "h: " << Water->hmass() << std::endl;
```

`printValues` is a function I made to display several values.
The `ph` and the `pT` input should give the same result (exactly the same to the displayed decimals).

Here are the results:

``` C++
1) ExternalMedia Fluid Constants

MediumName = Helium, libraryName = CoolProp, substanceName = He
MolarMass = 0.0040026
CriticalTemperature = 5.1953
CriticalPressure = 227600
CriticalMolarVolume = 5.51572e-005


2.0)  ExternalMedia Helium pT input
temperature = 4
velocityOfSound = 230.994
isobaric expansion coefficient = 725.828
specificHeatCapacityCp = 7.6248e+006
specificHeatCapacityCv = 2274.7
density = 140.628
density_derh_p = -0.00351094
density_derp_h = 4.37074e-005
dynamicViscosity = 2.46614e-006
specificEnthalpy = 7430.89
isothermalCompressibility = 0.00377474
thermalConductivity = 0.0297842
pressure = 400000
specificEntropy = 1324.08
phase = 2

2.1)  ExternalMedia Helium ph input
temperature = 4
velocityOfSound = 230.994
isobaric expansion coefficient = 0.0814328
specificHeatCapacityCp = 3261.73
specificHeatCapacityCv = 2274.7
density = 140.628
density_derh_p = -0.00351094
density_derp_h = 4.37074e-005
dynamicViscosity = 3.96943e-006
specificEnthalpy = 218.146
isothermalCompressibility = 1.91096e-007
thermalConductivity = 0.0204246
pressure = 400000
specificEntropy = -488.182
phase = 1
2.2) CoolProp AbstractState Helium
h: 218.146
```

We can see that the `pT` input gives wrong values (only `p` and `T` are correct, but they are the input, velocity of sound Cv and rho derivatives are also the same, but I guess it is because they do not vary a lot between the two points).

The strange thing is that the `state->update(CoolProp::PT_INPUTS,p,T);` doesn't make any errors, and if I modify the code to print some text before and after, the printing is done (so the line should be executed), and as the 2.2 step shows, it should make the correct update.

I don't get why it's not updating correctly.

**Comment by ibell** [comment]
Have you tried turning on debugging output?  Does that give you any
interesting information?

To confirm, these inputs actually work fine when you use PropsSI function,
right?  As a test, what about when you call PropsSI function from the
Modelica wrapper code?

**Comment by jowr** [comment]
What about the phase specification? Does the p,T solver end up somewhere else than the p,h solver due to an imposed phase in the second case?

**Comment by JonWel** [comment]
@ibell Yes, I tried debug:

``` C++
TwoPhaseMedium_setState_pT_C_impl(4e5, 4, pointer, "Helium", "CoolProp", "Helium|debug=100");
printValues(pointer);
```

``` C++
debug has the value of 100
Check passed, reducing Helium|debug=100 to fluid Helium, with HEOS backend.
Setting constants for fluid Helium
Setting near-critical saturation conditions for fluid Helium
setSat_p(2.2737239999999999e+005)
setState_pT(p=4.0000000000000000e+005,T=4.0000000000000000e+000)
At the end of postStateChange
Setting pressure to 400000.000821
Setting temperature to 4.000000
Setting density to 140.628263
Setting enthalpy to 7430.890839
Setting entropy to 1324.077157
temperature = 4
velocityOfSound = 230.994
isobaric expansion coefficient = 725.828
specificHeatCapacityCp = 7.6248e+006
specificHeatCapacityCv = 2274.7
density = 140.628
density_derh_p = -0.00351094
density_derp_h = 4.37074e-005
dynamicViscosity = 2.46614e-006
specificEnthalpy = 7430.89
isothermalCompressibility = 0.00377474
thermalConductivity = 0.0297842
pressure = 400000
specificEntropy = 1324.08
phase = 2
```

It shows that `p` and `T` are the correct value when sending to the state update, and that the `postStateChange` do not retrieve the correct values for enthalpy and entropy.

For `PropsSI`, I just added these to the C++ test file I use for externalmedia:

``` C++
std::cout << "9.3) CoolProp PropsSI Helium" << std::endl;
std::cout << "h: " << CoolProp::PropsSI("H","P",4e5,"T",4,"Helium") << std::endl;
```

And the results is correct:

```
9.3) CoolProp PropsSI Helium
h: 218.146
```

@jowr 
Here is a run with different input pair (both increased):

``` C++
std::cout << "\n9.0)  ExternalMedia Helium pT input" << std::endl; //|debug=100

TwoPhaseMedium_setState_pT_C_impl(8e5, 300, pointer, "Helium", "CoolProp", "Helium|debug=100");
printValues(pointer);
```

``` C++
9.0)  ExternalMedia Helium pT input
debug has the value of 100
Check passed, reducing Helium|debug=100 to fluid Helium, with HEOS backend.
Setting constants for fluid Helium
Setting near-critical saturation conditions for fluid Helium
setSat_p(2.2737239999999999e+005)
setState_pT(p=8.0000000000000000e+005,T=3.0000000000000000e+002)
At the end of postStateChange
Setting pressure to 800000.000278
Setting temperature to 300.000000
Setting density to 1.278887
Setting enthalpy to 7430.890839
Setting entropy to 1324.077157
temperature = 300
velocityOfSound = 1022.7
isobaric expansion coefficient = 725.828
specificHeatCapacityCp = 7.6248e+006
specificHeatCapacityCv = 3117.86
density = 1.27889
density_derh_p = -8.174e-007
density_derp_h = 1.59525e-006
dynamicViscosity = 2.46614e-006
specificEnthalpy = 7430.89
isothermalCompressibility = 0.00377474
thermalConductivity = 0.0297842
pressure = 800000
specificEntropy = 1324.08
phase = 2
```

It's clear that entropy and enthalpy are still exactly the same as the other input set (which is clearly not correct), but some of the other values have changed (like density which is correctly updated).

**Comment by JonWel** [comment]
What is really strange to me is that doing this:

``` C++
std::cout << "2.2) CoolProp AbstractState Helium" << std::endl;
shared_ptr<CoolProp::AbstractState> Water(CoolProp::AbstractState::factory("HEOS","Helium"));
Water->update(CoolProp::PT_INPUTS, 4e5, 4);
std::cout << "h: " << Water->hmass() << std::endl;
```

Gives the correct input, and I for me it is exactly what should be done in `ExternalMedia` (and the phase variable is not used in ph or pT, it may be an improvement to add this as CoolProp 5 allows to specify the phase: `state->specify_phase(CoolProp::iphase_liquid);`).

Maybe some strange caching problem?

**Comment by thorade** [comment]
2016-02-19 12:43 GMT+01:00 JonWel notifications@github.com:

> specificEnthalpy = 7430.89
> specificEntropy = 1324.08
> 
> It's clear that entropy and enthalpy are still exactly the same as the
> other input set (which is clearly not correct), but some of the other
> values have changed (like density).

What pressure and temperature do you get when you use these values as
input? Does it results in some special/known state?

**Comment by JonWel** [comment]
@thorade Good idea
High level interface:

``` Julia
julia> PropsSI("T","H",7430.890839,"S",1324.077157,"Helium")
5.171414983275838
julia> PropsSI("P","H",7430.890839,"S",1324.077157,"Helium")
227148.50677076244
```

With `ExternalMedia`:

``` C++
std::cout << "\n9.4)  ExternalMedia Helium hs input" << std::endl;
TwoPhaseMedium_setState_hs_C_impl(7430.890839, 1324.077157, 2, pointer, "Helium", "CoolProp", "Helium|debug=100");
printValues(pointer);
```

``` C++
9.4)  ExternalMedia Helium hs input
debug has the value of 100
Check passed, reducing Helium|debug=100 to fluid Helium, with HEOS backend.
Setting constants for fluid Helium
Setting near-critical saturation conditions for fluid Helium
setSat_p(2.2737239999999999e+005)
setState_hs(h=7.4308908389999997e+003,s=1.3240771569999999e+003)
Inputs in Brent [5.676800,2020.000000] do not bracket the root.  Function values are [7.183275,1023821.047816]
```

Which breaks (whereas the high level interface seems to work without problems).

But this time, the manual call to the functions gives the same error:

``` C++
std::cout << "9.5) CoolProp AbstractState Helium" << std::endl;
shared_ptr<CoolProp::AbstractState> helium(CoolProp::AbstractState::factory("HEOS","Helium"));
helium->update(CoolProp::HmassSmass_INPUTS, 7430.890839, 1324.077157);
std::cout << "T: " << helium->T() << " ?" << std::endl;
std::cout << "P: " << helium->p() << " ?" << std::endl;
```

(It breaks at the same error message in Solvers.cpp Brent(...) ).

`HmassSmass_INPUTS` is from here: http://www.coolprop.org/_static/doxygen/html/namespace_cool_prop.html#a58e7d98861406dedb48e07f551a61efba161bfc154732cc02ea7d46087f545691

**Comment by JonWel** [comment]
PropsSI is also crashing when using from the C++ code:

``` C++
std::cout << "9.6) CoolProp PropsSI Helium" << std::endl;
std::cout << "T: " << CoolProp::PropsSI("T","H",7430.890839,"S",1324.077157,"Helium") << std::endl;
std::cout << "P: " << CoolProp::PropsSI("P","H",7430.890839,"S",1324.077157,"Helium") << std::endl;
```

``` C++
9.6) CoolProp PropsSI Helium
T: 1.#INF
P: 1.#INF
```

Maybe a 32/64 bit or Windows/Linux problem? (the Julia code is compiled and executed on a Linux 64 bit whereas the C++ code is compiled and executed on a Windows XP virtual machine (I didn't have time yet to set up everything in a more up to date W10 64bit virtual machine)).

**Comment by ibell** [comment]
Helium is hard.  You can see that we still have plenty of problems with
Helium:
http://www.coolprop.org/dev/fluid_properties/fluids/Helium.html#consistency-plots

But it's MUCH better than before.  You might want to try your examples
again.  I fixed a bunch of issues with the flash routines.

**Comment by JonWel** [comment]
@ibell This is not linked to Helium I think. Here is an example with Water:

``` C++
std::cout << "\n9.0)  ExternalMedia Water pT input" << std::endl; //|debug=100
TwoPhaseMedium_setState_pT_C_impl(4e5, 4, pointer, "Water", "CoolProp", "Water|debug=100");
std::string err2 = CoolProp::get_global_param_string("errstring");
std::cout << err2 << std::endl;
printValues(pointer);

std::cout << "\n9.1)  ExternalMedia Water pT input 2" << std::endl;
TwoPhaseMedium_setState_pT_C_impl(4e5, 400, pointer, "Water", "CoolProp", "Water|debug=100");
printValues(pointer);

std::cout << "9.2) CoolProp AbstractState Water" << std::endl;
shared_ptr<CoolProp::AbstractState> Water(CoolProp::AbstractState::factory("HEOS","Water"));
Water->update(CoolProp::PT_INPUTS, 4e5, 4); // SI units
std::cout << "T: " << Water->T() << std::endl;
std::cout << "P: " << Water->p() << std::endl;
std::cout << "rho: " << Water->rhomass() << std::endl;
std::cout << "h: " << Water->hmass() << std::endl;
```

``` C++
9.0)  ExternalMedia Water pT input
debug has the value of 100
Check passed, reducing Water|debug=100 to fluid Water, with HEOS backend.
Setting constants for fluid Water
Setting near-critical saturation conditions for fluid Water
setSat_p(2.2041936000000000e+007)
setState_pT(p=4.0000000000000000e+005,T=4.0000000000000000e+000)
Enthalpy is 1918653.759607
Setting pressure to 400000.000821
Setting temperature to 4.000000
Setting pressure to 4828920137011673200000000000.000000
Setting temperature to 4.000000
Setting enthalpy to 218.146205
Setting enthalpy to 1918653.759607
At the end of postStateChange
Setting pressure to 4828920137011673200000000000.000000
Setting temperature to 4.000000
Setting density to 1107.826242
Setting enthalpy to 1918653.759607
Setting entropy to 4151.118824

temperature = 4
velocityOfSound = -1.#IND
isobaric expansion coefficient = 7.63307
specificHeatCapacityCp = 3.11344e+006
specificHeatCapacityCv = -2.73014e+037
density = 1107.83
density_derh_p = 2.79126e-038
density_derp_h = -3.4175e-040
dynamicViscosity = 5.62293e-005
specificEnthalpy = 1.91865e+006
isothermalCompressibility = 2.40226e-005
thermalConductivity = 0.97184
pressure = 4.82892e+027
specificEntropy = 4151.12
phase = 2

9.1)  ExternalMedia Water pT input 2
setState_pT(p=4.0000000000000000e+005,T=4.0000000000000000e+002)
Enthalpy is 1918653.759607
Setting pressure to 4828920137011673200000000000.000000
Setting temperature to 4.000000
Setting pressure to 4828920137011673200000000000.000000
Setting temperature to 4.000000
Setting enthalpy to 1918653.759607
Setting enthalpy to 1918653.759607
At the end of postStateChange
Setting pressure to 4828920137011673200000000000.000000
Setting temperature to 4.000000
Setting density to 1107.826242
Setting enthalpy to 1918653.759607
Setting entropy to 4151.118824
temperature = 4
velocityOfSound = -1.#IND
isobaric expansion coefficient = 7.63307
specificHeatCapacityCp = 3.11344e+006
specificHeatCapacityCv = -2.73014e+037
density = 1107.83
density_derh_p = 2.79126e-038
density_derp_h = -3.4175e-040
dynamicViscosity = 5.62293e-005
specificEnthalpy = 1.91865e+006
isothermalCompressibility = 2.40226e-005
thermalConductivity = 0.97184
pressure = 4.82892e+027
specificEntropy = 4151.12
phase = 2
9.2) CoolProp AbstractState Water
# crash: Solver.cpp line 329
#throw ValueError(format("Inputs in Brent [%f,%f] do not bracket the root.  Function values are [%f,%f]",a,b,fa,fb));
# Crash is due to lack of error handling in this way I used CoolProp
```

I changed the temperature between the two runs, the debug detail write the PT has the right temperature as input, but the temperature is not updated at the end, and a lot of values are still the same.

It is possible to test `ExternalMedia` without having `Dymola` by using the C++ functions directly from an other C++ file like this: http://pastebin.com/9D2BVRpW (comment or uncomment the part of interest).

Should CoolProp compile well under Visual Studio 2015? (I wanted to try to compile the same code on a W10 64bit with VS 2015 but I had some issues, maybe they are solved by now).

**Comment by casella** [comment]
I also had a similar comment. Helium in that region is basically an ideal gas, though with a bit unusual values for density and temperature. There must be something wrong with the interpolation functions.

**Comment by JonWel** [comment]
@ibell Could you check [here](https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.cpp#L162) and [here](https://github.com/CoolProp/ExternalMedia/blob/master/Projects/Sources/coolpropsolver.h#L29) if you think the way I initialise the CoolProp state is fully consistent?

I'm more fearing some kind of partial update when using PT_inputs than a problem with helium.

Does visual studio allows a tracing of the state update? If yes, how can I do?
I'm using a Visual Studio 2010 on XP virtual machine (I did also try VS 2015 on W10 but not yet succeed to compile).

**Comment by jowr** [comment]
Have you tried with smart pointer instead of ordinary ones? I have no idea why it shouldn't work the way you wrote it, but it might be worth a try.

**Comment by jowr** [comment]
You have to do something likes this:

``` C++
#include "crossplatform_shared_ptr.h"
#include "AbstractState.h"

shared_ptr<CoolProp::AbstractState> AS(CoolProp::AbstractState::factory(lib_name,fluid));
// ... and later in the code
AS.reset(CoolProp::AbstractState::factory(new_lib_name,new_fluid));
```

Afterwards, you can use the dot operator `.` to access the smart pointer object and contained object (the state) is accessible via the normal pointer operator `->` as in `AS->update(...`.

**Comment by JonWel** [comment]
@jowr Good idea.

The way to implement it is however a bit unclear to me.
The "state" is currently instantiated by pointer to the a `CoolProp::AbstractState` class in the header.:

``` C++
class CoolProp::AbstractState *state;
```

The shared pointer has it's own type (`std::tr1::shared_ptr`) but should point to a `CoolProp::AbstractState` class as I understand.

But If I do something like this:

``` C++
shared_ptr<CoolProp::AbstractState> AS(CoolProp::AbstractState::factory(backend, this->substanceName));
this->state = *AS;
```

Visual Studio complains on the line `this->state = *AS;` that it can't convert from `CoolProp::AbstractState` to `CoolProp::AbstractState *`
With only this `*` which differ.

If I don't set the `*` at that line (so `this->state = AS;`), there is also a conversion problem as the type of the shared pointer is `std::tr1::shared_ptr` which cannot be automatically converted to `CoolProp::AbstractState *`.

(By the way, I would prefer a solution that involves only one variable instead of `AS` and `this->state`)

**Comment by jowr** [comment]
I think you misunderstood me. You can replace 

``` C++
class CoolProp::AbstractState *state;
//...
this->state = CoolProp::AbstractState::factory(backend, this->substanceName);
```

with 

``` C++
shared_ptr<CoolProp::AbstractState> state;
//...
this->state.reset(CoolProp::AbstractState::factory(backend, this->substanceName));
//... and remove delete state; from the destructor
```

You will end up with only one variable that you can call just like you are used to.

**Comment by jowr** [comment]
Have a look at  61d0fd3, I included the changes there, but I did not do any testing.

**Comment by ibell** [comment]
That looks like the right idea to me.

**Comment by JonWel** [comment]
@jowr @ibell Compilation has errors now:
```C++
c:\users\johndoe\source\repos\externalmedia\externals\coolprop.git\include\CPnumerics.h(403): error C2589: '(': illegal token on right side of '::' (compiling source file Sources\solvermap.cpp)
c:\users\johndoe\source\repos\externalmedia\externals\coolprop.git\include\CPnumerics.h(403): error C2059: syntax error: '::' (compiling source file Sources\solvermap.cpp)
```

Which cause this error in Dymola:
```C++
ExternalMediaLib.lib(externalmedialib.obj) : error LNK2019: unresolved external symbol "public: static class BaseSolver * __cdecl SolverMap::getSolver(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?getSolver@SolverMap@@SAPAVBaseSolver@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00@Z) referenced in function _TwoPhaseMedium_getMolarMass_C_impl
dymosim.exe : fatal error LNK1120: 1 unresolved externals
```

This is on the CoolProp part. Should I open an issue?

**Comment by ibell** [comment]
Yes please.  What compiler do you use?

**Comment by JonWel** [comment]
@ibell The ExternalMedia bat file for VS 2010 and 2015 (both giving this same error).
When I tried to compile CoolProp the Linux way (to make the library for Julia), I did not get that error.

**Comment by JonWel** [comment]
I don't really get what's happening.
The line it complains about in `CPnumerics.h` is the definition of the function:
```C++
inline bool double_equal(double a, double b){return std::abs(a - b) <= 1 * DBL_EPSILON * std::max(std::abs(a), std::abs(b));};
```

But it gives the error when `(compiling source file Sources\solvermap.cpp)` which is a file from `ExternalMedia` but I don't see any use of this `double_equal` function in this file.

And the shared library compilation of CoolProp under Linux is working without any problem, so I'm not that sure it is really a CoolProp problem.

**Comment by ibell** [comment]
Maybe there is a header missing needed for std::max or std::abs

**Comment by JonWel** [comment]
So now that it compiles again (thanks @ibell ), I tested the library again in Dymola with the shared pointer and it gives the same results as with the Abstract Class.
So this doesn't seems to had an impact on this problem.

**Comment by ibell** [comment]
What compiler are you building with?

**Comment by JonWel** [comment]
This was with Visual Studio 2010 on a 32 bit xp virtual machine.

I'm quite busy this week as following a [practical course](https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950199724&pSpracheNr=1&pMUISuche=FALSE) on C++ (It should helps me a bit, they use Eclipse which is a bit different from visual studio, but it also familiarise me a bit more with IDE and give me a better theoretical background).

**Comment by ibell** [comment]
Well I'm certainly not in any rush, but I'd like to help if I can.  So let
me know how I can try to build your example that doesn't work and I'll
debug.

**Comment by JonWel** [comment]
@ibell As I understand you don't have access to Dymola, the best may be to use the test file I use for debugging: http://pastebin.com/9D2BVRpW

Instructions to set up Visual Studio are here: http://pastebin.com/zpWVc40i

(I didn't update the test file to the newest I use, but the main functions to try are present. I'll try to update and explain a bit better when I'll have a bit more time. This C++ course is very interesting, but also takes time).

**Comment by ibell** [comment]
You should make a CMake configuration file for this.  Much simpler, and no
fighting with flags.  Also helpful for testing on other platforms and
compilers.

**Comment by JonWel** [comment]
I added some line in the `coolpropsolver.cpp` file in the function `CoolPropSolver::setState_pT(double &p, double &T, ExternalThermodynamicState *const properties){`:

``` C++
        state->update(CoolProp::PT_INPUTS,p,T);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
        std::cout << format("state->keyed_output(CoolProp::get_parameter_index(Hmass)) = %0.16e\n",state->keyed_output(CoolProp::get_parameter_index("Hmass")));
        state->update(CoolProp::HmassP_INPUTS,1000,p);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
        std::cout << format("state->keyed_output(CoolProp::get_parameter_index(Hmass)) = %0.16e\n",state->keyed_output(CoolProp::get_parameter_index("Hmass")));
        state->update(CoolProp::PT_INPUTS,p,T);
        std::cout << format("state->hmass() = %0.16e\n",state->hmass());
        std::cout << format("state->keyed_output(CoolProp::get_parameter_index(Hmass)) = %0.16e\n",state->keyed_output(CoolProp::get_parameter_index("Hmass")));
```

The first line is the normal line (to make the PT update), the two seconds display the mass enthalpy  (two different ways to call to check if result where still the same).
The two other updates are to experiment and try to find where things get wrong.

And here is the result:

``` C++
setState_pT(p=5.0000000000000000e+005,T=2.7300000000000000e+002)
state->hmass() = 7.4308908389366325e+003
state->keyed_output(CoolProp::get_parameter_index(Hmass)) = 7.4308908389366325e+
003
state->hmass() = 9.9999999999677345e+002
state->keyed_output(CoolProp::get_parameter_index(Hmass)) = 9.9999999999677345e+
002
state->hmass() = 1.4245087609712468e+006
state->keyed_output(CoolProp::get_parameter_index(Hmass)) = 1.4245087609712468e+
006
At the end of postStateChange
Setting pressure to 500000.000000
Setting temperature to 273.000000
Setting density to 0.879374
Setting enthalpy to 1424508.760971
Setting entropy to 24204.199274
```

We see that the call with `hmass()` is the same as the one with `keyed_output()` (the later is used in the high level interface which gives correct results, and I guess call the first one internally).

But more interesting is that the second call of PT input gives the right result this time:

``` julia
julia> PropsSI("Hmass","P",5e5,"T",273,"Helium")
1.4245087609712468e6
```

This good result do not appear if I just update two times the same PT input, but happen with this case where a HmassP is done in between.

**Comment by JonWel** [comment]
``` C++
        state->update(CoolProp::PT_INPUTS,p,T);
        state->clear();
        state->update(CoolProp::PT_INPUTS,p,T);
```

Gives wrong result, but:

``` C++
        state->update(CoolProp::PT_INPUTS,p,T);
        state->update(CoolProp::HmassP_INPUTS,1000,p);
        state->clear();
        state->update(CoolProp::PT_INPUTS,p,T);
```

Gives correct result after the last update.

**Comment by JonWel** [comment]
@ibell Do I need to make some kind of initialisation of the state other than:

```
state.reset(CoolProp::AbstractState::factory(backend, this->substanceName));
```

?

Do you understand why the first call to `state->update(CoolProp::PT_INPUTS,p,T);` does not update correctly, but if a `HmassP_INPUTS` is done, than  the `PT_INPUTS` is than updating correctly (even if a `clear()` is made between theses two different kind of updates).

This is quite puzzling for me as when I use `PropsSI`, I get directly the right output (whereas it also use the `PT_INPUTS` internally).

(I recall that I experience this behaviour with the  `PT_INPUTS` also with water, so this is not specific to helium)

**Comment by ibell** [comment]
No, its very weird.  I'll try to take a look.  Can you open an issue on
CoolProp and link to this one?  It's easier to keep track that way.

By the way, are you using the most up-to-date version of CoolProp?  I had
to fix one thing with caching of variables, and maybe its related to that.

**Comment by JonWel** [comment]
I go update everything and test again.
